[build]
  publish = "/"
  command = "echo 'No build command needed for static files'"

[build.environment]
  NODE_VERSION = "18"
  # Default values for environment variables - should be set in Netlify UI for production
  BACKEND_URL = "https://d007-102-213-68-144.ngrok-free.app"
  SOLANA_RPC_URL = "https://solana-mainnet.g.alchemy.com/v2/C6TRj1OIjI5oSZ7ocT5rhhDXguSkO0mN"
  CONNECTION_KEY = "601"
  GROUP_CHAT_ID = "-4872265548"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade" 